### ISSUE TITLE
Send action to route

### ISSUE THREAD

**Issue by davidpike7** [mitchlloyd/ember-islands#20]
I'm including a component like so: 
```html
<div
  data-component='user-profile'
  data-attrs='{"name": "Sally User", "id": "4"}'>
</div>
```

I'd like to bubble an action from this component up to the route. What's the best way of accomplishing this?

**Comment by mitchlloyd** [comment]
I consider "bubbling actions to routes" legacy Ember behavior because it does not work with closure actions. [There are some workaround solutions](https://github.com/DockYard/ember-route-action-helper), but in general it's not something I've done in a while.

So then how do you send an action to a controller? Well here again, controllers are a vestige of the past. Surely we're less than 8 months aways top-level components in our Ember apps :trollface: 

So from there I can start to imagine all sorts of things to do, but I should probably know what you're use case is before suggesting anything. So what are you trying to do with this action?

**Comment by davidpike7** [comment]
We've got an existing ember application (1.13.*) that I'm trying to incorporate in a CMS website to utilise some of the components and functionality. We've got several form modals which (I think) would be a perfect candidate for ember islands.

The application was written a while ago and so is a bit legacy-esque in its approach for opening the modals.

Currently we do the following:

Trigger `openModal` action in a template with a parameter for the modal of say `need-help`. This bubbles to the application controller which then does something along the lines of:

```javascript            
return this.render(modalName, {
  into: 'application',
  outlet: 'modal'
});
```

The modal itself has a controller and includes the modal component inside it which wraps the content in magnific popup.

If another modal is triggered the application route removes the old controller and instantiates the new one.

**Comment by mitchlloyd** [comment]
Yeah I was looking at the guides and noticing that they [don't talk about sending actions to routes](https://guides.emberjs.com/v2.4.0/templates/actions/).

I think [ember-route-action-helper](https://github.com/DockYard/ember-route-action-helper) is going to work for you. If that doesn't work, probably the best thing to do would be to create a service to interface with your application route to call openModal.

**Comment by davidpike7** [comment]
Thanks for the help.

I've gone with using a service to interface with the application route and its working great. All very seamlessly.

Ember Islands is great!

**Comment by mitchlloyd** [comment]
Ember Islands, clawing its way back to the top!
