### ISSUE TITLE
[Question] using ember-islands in a non cli project

### ISSUE THREAD

**Issue by mtermoul** [mitchlloyd/ember-islands#21]
Hello,
I have a Django application, and I included ember libs to be able to use ember feature. So far I was able to manage by inserting ember app inside existing:
`<div id="ember-content">`

using the rootElement as:

```
var App = Ember.Application.create({
    LOG_TRANSITIONS: true,
    autoinit: false,
    rootElement: '#ember-content',
});
```
So my problem is that I want to place ember components on existing server elements, and I was wondering how to use ember-islands in a non cli project.

Currently I have index.html page (server side page) which has script tags for all ember js libraries. So I am able to use ember without cli.

**Comment by mitchlloyd** [comment]
_Disclaimer: This library is designed to work with Ember CLI and not the globals-based Ember applications. This is because Ember CLI is one of the most compelling parts of the Ember ecosystem and the globals approach gets very little attention._

All that being said, I think this should work.

First off, `autoinit` is a relic of the past as far as I can tell. There is an `autoboot` option, but you shouldn't use either of these.

Ember Islands tries to fit into the natural development workflow of an Ember application as much as possible. It uses a booted Ember application to handle events (with the EventDispatcher) and it uses template rendering to kickoff rendering "island" components (using the `{{ember-islands}}` component). For the EventDispatcher to work, your island components must be placed inside `#ember-content`.

Make sure your DOM is on the page before your Ember app boots and that your component markers are inside of `#ember-content`.

If you could make a repo showing what you've tried I'd be happy to look at it. You should be able to replicate this approach by just creating an `index.html` file with static HTML and including an Ember build.

**Comment by mtermoul** [comment]
Thanks for the reply Mitch.
I have created a sample app to illustrate my issue.

https://github.com/mtermoul/django-ember-app


As you can examine, this is Django app. the base.html template has all the js files for jquery, bootstrap, and ember. The app.js is the main application file for ember app, controllers, routers, components....
The home.html is the default index page, which I defined the handlebar templates inside.

Please take a look and let me know if any question.

Thanks again.

**Comment by mitchlloyd** [comment]
Ok, ran through the install instructions but I'm not very familiar with Python setups and I may be missing some software. However, the issue seems apparent: you're rendering your Ember app inside of `#ember-content` and your page-footer is rendered outside of the Ember application.

The reason you're seeing this issue:

> The issue is that ember islands is placing the page-footer component on the #page-footer-section, but the actions on this component is not firing

Is because of what I described above:

> For the EventDispatcher to work, your island components must be placed inside #ember-content
>
> Make sure your DOM is on the page before your Ember app boots and that your component markers are inside of #ember-content.

I'm not sure exactly what you're trying to do, but I have a feeling that if you delete [this line](https://github.com/mtermoul/django-ember-app/blob/master/shadow/static/js/app.js#L3) you'll find success.

I'm impressed that you've made it so far with this setup! Now that you have a proof of concept together you might want to explore using Ember CLI because I think in the long term you'll be happier.

**Comment by mitchlloyd** [comment]
Closing this issue for now. Let me know if there is anything else I can help with.
