### ISSUE TITLE
Vague Implementation in Rails

### ISSUE THREAD

**Issue by hiimtaylorjones** [mitchlloyd/ember-islands#32]
Hey there,

I'm attempting to integrate Ember Islands with an existing Rails application that's potentially using Ember-Cli-Rails for Ember distribution. Could you provide some more insight on what the best way to leverage Ember Islands to do this? I'm having trouble finding a way to best implement this currently. 

I'd love to use the ensuing conversation to add to the current documentation. Maybe under a "Guides" section or something like that!

**Comment by mitchlloyd** [comment]
It looks like the ember-cli-rails gem/addons has a lot of documentation and structure around integrating and deploying an Ember app with Rails. However it doesn't look like you'll just be able to use the `mount_ember_app` route method in your Rails rendered pages since you don't control that template.

Perhaps using this template as an example you could load your Ember app onto an existing page? https://github.com/thoughtbot/ember-cli-rails/blob/d73b72f8d93a4e38b0b67c60f26846d059021fac/app/views/ember_cli/ember/index.html.erb 

As far as Ember Islands goes, as long as you have the placeholder in your template and you're able to load the javascript files for your Ember app on the page it should work.

**Comment by mitchlloyd** [comment]
Not sure if you were able to find a good way to do this, but if I remember correctly I don't think this was an Ember Islands issue per se. Let me know if I should reopen.
