### ISSUE TITLE
Example of setting up in a Rails app

### ISSUE THREAD

**Issue by ClayShentrup** [mitchlloyd/ember-islands#38]
I'm sorry if this isn't the best way of adding a feature request. I loved your talk and the readme on this project looks great. I just can't get it working on a legacy Rails app. I'm including the vendor and application files but no luck. Thanks.

**Comment by mitchlloyd** [comment]
@ClayShentrup Sorry to hear that you're having trouble. Recently someone Tweeted an article to me that might help with your Rails setup: https://labs.kollegorna.se/blog/2017/01/rendering-ember-components-from-rails/.

Closing this issue since setting up JavaScript assets on people's backend is beyond the scope of this project.
