### ISSUE TITLE
The Future of this Addon + Glimmer.js 

### ISSUE THREAD

**Issue by blimmer** [mitchlloyd/ember-islands#42]
Since Glimmer.js provides the ability to render web-component compatible / ember-y components in server-rendered apps, does that change what this project is trying to accomplish in the future?

**Comment by mitchlloyd** [comment]
As of today Glimmer has no bearing on this addon or its direction. This addon isn't compatible with Glimmer and Glimmer users have no need for this addon. However, Glimmer's web-component build doesn't work with Ember components but this addon does.

Ultimately I made this plugin because Ember does not expose primitives that let users render components in isolation as React, Vue, and most other JavaScript frameworks do. As soon as that changes I'll deprecate this plugin in favor of whatever the conventional solution is. However, I've learned not to prepare for future Ember features (or really any future work beyond my control).

That being said, if anyone wants to fork this project or work on a new branch that does something with Glimmer I would be happy to support it any way I can. Do you have any particular features or changes in mind?

**Comment by blimmer** [comment]
Thanks for the info, I was genuinely curious if (and how) the announcement of glimmer changed any ideas about how this addon might change. When I first looked into ember-islands, it was because I needed some moderately-complex web-components, but none of the other features of Ember. It seems like glimmer is a good replacement for that specific use-case, but you're right that this addon provides a lot more behavior outside of what glimmer has.

I'll go ahead and close this issue for now - thanks for the info!
