### ISSUE TITLE
Allow top-level components to yield to template blocks

### ISSUE THREAD

**Issue by sidfarkus** [mitchlloyd/ember-islands#6]
Components that use the `{{yield}}` helper in their template should be able to specify a template to evaluate in the yield block. 

If possible it would be interesting to change the component div to a script tag that could take HTMLBars embedded directly with the component similar to a standard Ember app.  `ember-islands` could prepend the component div and wire up the template automatically.

This would help apps that are slowing migrating to Ember to write isolated containers like modals and list components.

**Comment by mitchlloyd** [comment]
I think using HTMLBars templates inside of script tags would be possible and could be pretty nice. However, that's a pretty large conceptual change from the original idea of this library.  In short, that idea is that you can create a thin bridge between your server code and client code by passing the name of a component and all of the data that component needs to render. Having dynamic templates on the server means that you'll have some of your templates in ember-cli and some of your templates in your server code.

Doing this also means users would need to include the ember-template-compiler in their production builds since the templates rendered on the server wouldn't be known by Ember until run time.

The workaround today would be to pass your static HTML into the `data-attrs` portion of an element and render it as safe html `{{{<strong>hello</strong>}}}`. Obviously this means that you couldn't have dynamic HTMLBars content in this markup.

I could be convinced to work on compiling and rendering dynamic templates from the server at run time, but I would be interested in looking at a specific use case or two first where this approach has a clear advantage over what is in place now. Could you provide some more information about your modal use case for instance?

**Comment by sidfarkus** [comment]
We'd like to be able to write code that is as close as possible to our existing server-side templates.  For example we have a `ModalBuilder` that helps us build a modal dialog:

```
= modal('my-modal').build do |m|
  - m.header do
    %h2 some header
  %p Content here specific to this view
```
We'd like to keep the inner markup in the same Rails view but replace the server-side helper with an Ember component.  I'm open to suggestions as to workarounds but we don't love the idea of splitting our (page specific) rendering markup between the Rails view and the Ember component/templates.  This may be a situation that we should bite the bullet and convert the entire page to Ember however there is a lot of inertia there.

**Comment by mitchlloyd** [comment]
Ok, that's the case I was hoping for. One thing you could do is modify your Rails helper to jam all that built markup into the `data-attrs` attribute so that it gets to your component. I'm not sure how to do that with your builder syntax, but it seems like it should be possible using `capture`.

As far as better solution with ember-islands, what do you think of extracting the innerHTML of the static element and putting that into an `innerContent` property on the component?

So you would build an element like this with your server:

```haml
%div(data-component='modal-dialog' data-attrs='{"confirmText": "Save it!"}')
  %h2 Some Header
  %p Some content here
```

And then ember-islands would come along and you could render this with a component like this:

```handlebars
<div class='special-modal-markup'>
  {{{innerContent}}}
</div>
```

It seems like you would not want to show that content on your page until ember-islands picked it up. You could put that in a script tag so that it is hidden or your could add a css rule to hide all elements with a `data-component` attribute.

Would that work for you?

**Comment by sidfarkus** [comment]
That looks like exactly what we'd need for most of our functionality.

**Comment by mitchlloyd** [comment]
I just pushed this feature to master. Would you mind trying it out there before I make a release for it?

**Comment by mitchlloyd** [comment]
@sidfarkus Did you have a chance to check this out yet?

**Comment by sidfarkus** [comment]
@mitchlloyd Sorry, I've been tied up with some other things; I'll give it a run this weekend and let you know if it looks good.  Thanks again for the great gem!

**Comment by TeknoFiend** [comment]
Just tried this out and it worked great for a test component.  Thanks @mitchlloyd !
